[2023-11-05T00:48:29.721+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v02/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=2nd_task2 permission to 509
[2023-11-05T00:48:29.779+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v02/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=2nd_task2 permission to 509
[2023-11-05T00:48:29.902+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v02.2nd_task2 scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-05T00:48:29.924+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v02.2nd_task2 scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-05T00:48:29.925+0000] {taskinstance.py:1361} INFO - Starting attempt 6 of 6
[2023-11-05T00:48:29.956+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 2nd_task2> on 2023-11-02 00:00:00+00:00
[2023-11-05T00:48:29.963+0000] {standard_task_runner.py:57} INFO - Started process 7689 to run task
[2023-11-05T00:48:29.968+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v02', '2nd_task2', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data2.py', '--cfg-path', '/tmp/tmphyfo0no7']
[2023-11-05T00:48:29.974+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask 2nd_task2
[2023-11-05T00:48:30.052+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v02/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=2nd_task2 permission to 509
[2023-11-05T00:48:30.057+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 159 for task 2nd_task2 ([Errno 5] Input/output error: '/opt/airflow/logs/dag_id=fetch_google_data_v02/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=2nd_task2/attempt=6.log'; 7689)
[2023-11-05T00:48:30.101+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T00:48:30.141+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
