[2023-11-08T00:31:34.828+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-08T00:31:16.239048+00:00/task_id=2nd_task permission to 509
[2023-11-08T00:31:34.944+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-08T00:31:16.239048+00:00/task_id=2nd_task permission to 509
[2023-11-08T00:31:35.029+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v01.2nd_task manual__2023-11-08T00:31:16.239048+00:00 [queued]>
[2023-11-08T00:31:35.055+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v01.2nd_task manual__2023-11-08T00:31:16.239048+00:00 [queued]>
[2023-11-08T00:31:35.056+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-08T00:31:35.084+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 2nd_task> on 2023-11-08 00:31:16.239048+00:00
[2023-11-08T00:31:35.095+0000] {standard_task_runner.py:57} INFO - Started process 6958 to run task
[2023-11-08T00:31:35.102+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'check_S3_minio_bucket_v01', '2nd_task', 'manual__2023-11-08T00:31:16.239048+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/check_S3_bucket.py', '--cfg-path', '/tmp/tmpe5vh8qgc']
[2023-11-08T00:31:35.107+0000] {standard_task_runner.py:85} INFO - Job 402: Subtask 2nd_task
[2023-11-08T00:31:35.209+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-08T00:31:16.239048+00:00/task_id=2nd_task permission to 509
[2023-11-08T00:31:35.216+0000] {task_command.py:416} INFO - Running <TaskInstance: check_S3_minio_bucket_v01.2nd_task manual__2023-11-08T00:31:16.239048+00:00 [running]> on host 326a1fe25163
[2023-11-08T00:31:35.978+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='check_S3_minio_bucket_v01' AIRFLOW_CTX_TASK_ID='2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T00:31:16.239048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T00:31:16.239048+00:00'
[2023-11-08T00:31:35.983+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T00:31:35.987+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install urllib3']
[2023-11-08T00:31:36.018+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T00:31:38.783+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-11-08T00:31:39.289+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (1.26.17)
[2023-11-08T00:31:48.297+0000] {subprocess.py:93} INFO - 
[2023-11-08T00:31:48.299+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-11-08T00:31:48.300+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-11-08T00:31:48.677+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-08T00:31:48.713+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=check_S3_minio_bucket_v01, task_id=2nd_task, execution_date=20231108T003116, start_date=20231108T003135, end_date=20231108T003148
[2023-11-08T00:31:48.745+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-08T00:31:48.817+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
