[2023-11-05T00:13:24.499+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T00:13:24.548+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T00:13:24.615+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-05T00:13:24.633+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_data_v01.3rd_task scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-05T00:13:24.635+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 6
[2023-11-05T00:13:24.658+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 3rd_task> on 2023-11-02 00:00:00+00:00
[2023-11-05T00:13:24.666+0000] {standard_task_runner.py:57} INFO - Started process 3359 to run task
[2023-11-05T00:13:24.670+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fetch_google_data_v01', '3rd_task', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmpy5nq9pex']
[2023-11-05T00:13:24.673+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask 3rd_task
[2023-11-05T00:13:24.750+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=3rd_task permission to 509
[2023-11-05T00:13:24.755+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 138 for task 3rd_task ([Errno 5] Input/output error: '/opt/airflow/logs/dag_id=fetch_google_data_v01/run_id=scheduled__2023-11-02T00:00:00+00:00/task_id=3rd_task/attempt=4.log'; 3359)
[2023-11-05T00:13:24.803+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T00:13:24.952+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
