[2023-11-08T00:35:37.034+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-08T00:35:15.437574+00:00/task_id=2nd_task permission to 509
[2023-11-08T00:35:37.085+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-08T00:35:15.437574+00:00/task_id=2nd_task permission to 509
[2023-11-08T00:35:37.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v01.2nd_task manual__2023-11-08T00:35:15.437574+00:00 [queued]>
[2023-11-08T00:35:37.163+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v01.2nd_task manual__2023-11-08T00:35:15.437574+00:00 [queued]>
[2023-11-08T00:35:37.164+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-08T00:35:37.183+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 2nd_task> on 2023-11-08 00:35:15.437574+00:00
[2023-11-08T00:35:37.189+0000] {standard_task_runner.py:57} INFO - Started process 8897 to run task
[2023-11-08T00:35:37.193+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'check_S3_minio_bucket_v01', '2nd_task', 'manual__2023-11-08T00:35:15.437574+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/check_S3_bucket.py', '--cfg-path', '/tmp/tmpamm8jia_']
[2023-11-08T00:35:37.196+0000] {standard_task_runner.py:85} INFO - Job 405: Subtask 2nd_task
[2023-11-08T00:35:37.255+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v01/run_id=manual__2023-11-08T00:35:15.437574+00:00/task_id=2nd_task permission to 509
[2023-11-08T00:35:37.262+0000] {task_command.py:416} INFO - Running <TaskInstance: check_S3_minio_bucket_v01.2nd_task manual__2023-11-08T00:35:15.437574+00:00 [running]> on host 326a1fe25163
[2023-11-08T00:35:37.380+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='check_S3_minio_bucket_v01' AIRFLOW_CTX_TASK_ID='2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T00:35:15.437574+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T00:35:15.437574+00:00'
[2023-11-08T00:35:37.384+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T00:35:37.387+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install urllib3']
[2023-11-08T00:35:37.410+0000] {subprocess.py:86} INFO - Output:
[2023-11-08T00:35:39.721+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-11-08T00:35:40.002+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (1.26.17)
[2023-11-08T00:35:50.152+0000] {subprocess.py:93} INFO - 
[2023-11-08T00:35:50.154+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-11-08T00:35:50.155+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-11-08T00:35:50.665+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-08T00:35:50.723+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=check_S3_minio_bucket_v01, task_id=2nd_task, execution_date=20231108T003515, start_date=20231108T003537, end_date=20231108T003550
[2023-11-08T00:35:50.798+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-08T00:35:50.928+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
