[2023-11-09T01:59:04.025+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v02/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=2nd_task permission to 509
[2023-11-09T01:59:04.081+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v02/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=2nd_task permission to 509
[2023-11-09T01:59:04.128+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v02.2nd_task scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-09T01:59:04.155+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_S3_minio_bucket_v02.2nd_task scheduled__2023-11-08T00:00:00+00:00 [queued]>
[2023-11-09T01:59:04.157+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-09T01:59:04.183+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): 2nd_task> on 2023-11-08 00:00:00+00:00
[2023-11-09T01:59:04.192+0000] {standard_task_runner.py:57} INFO - Started process 524 to run task
[2023-11-09T01:59:04.198+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'check_S3_minio_bucket_v02', '2nd_task', 'scheduled__2023-11-08T00:00:00+00:00', '--job-id', '452', '--raw', '--subdir', 'DAGS_FOLDER/check_S3_bucket.py', '--cfg-path', '/tmp/tmpyea1m11b']
[2023-11-09T01:59:04.202+0000] {standard_task_runner.py:85} INFO - Job 452: Subtask 2nd_task
[2023-11-09T01:59:04.310+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=check_S3_minio_bucket_v02/run_id=scheduled__2023-11-08T00:00:00+00:00/task_id=2nd_task permission to 509
[2023-11-09T01:59:04.319+0000] {task_command.py:416} INFO - Running <TaskInstance: check_S3_minio_bucket_v02.2nd_task scheduled__2023-11-08T00:00:00+00:00 [running]> on host a4fee2fb2c17
[2023-11-09T01:59:04.500+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Toema' AIRFLOW_CTX_DAG_ID='check_S3_minio_bucket_v02' AIRFLOW_CTX_TASK_ID='2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-08T00:00:00+00:00'
[2023-11-09T01:59:04.503+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-09T01:59:04.506+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install urllib3']
[2023-11-09T01:59:04.527+0000] {subprocess.py:86} INFO - Output:
[2023-11-09T01:59:06.563+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-11-09T01:59:06.880+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (1.26.17)
[2023-11-09T01:59:17.685+0000] {subprocess.py:93} INFO - 
[2023-11-09T01:59:17.686+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-11-09T01:59:17.688+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-11-09T01:59:18.192+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-09T01:59:18.262+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=check_S3_minio_bucket_v02, task_id=2nd_task, execution_date=20231108T000000, start_date=20231109T015904, end_date=20231109T015918
[2023-11-09T01:59:18.844+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-09T01:59:20.433+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
